name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    strategy:
      matrix:
        go-versions: ['1.19']
        platform: [ubuntu-20.04-ppc64le]
        environment-variables: [build/config/plain.sh]
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    steps:
    - name: Install Go
      uses: shahidhs-ibm/setup-go@ppc64le
      with:
        go-version: ${{ matrix.go-versions }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run presubmit checks
      run: |
        source ${{ matrix.environment-variables }}
        if [[ "${BUILD_PACKAGES}" != "" ]]; then sudo apt-get update; sudo apt-get install -y wget git curl patch make gcc; fi
        make build
        make -e presubmit
    - name: Run tests
      env:
        GOLANG_VERSION: ${{ matrix.go-versions }}
      run: |
        source ${{ matrix.environment-variables }}
        make test
